Unseen object image segmentation single frame update
au-rmr/aurmr_tahoma pull request #13
Opened 2023-03-28 00:41 UTC by Soofiyan

2023-04-02 17:00 UTC, markusgrotz commented on aurmr_perception/src/aurmr_perception/grasp_detection.py
> +sys.path.append("/home/aurmr/workspaces/uois_soofiyan_ws/src/segnetv2_mask2_former/UIE_main/mask2former_frame/")
Can you remove this ?

2023-05-09 00:13 UTC, markusgrotz requested changes

2023-05-09 00:13 UTC, markusgrotz commented on aurmr_perception/src/aurmr_perception/grasp_detection.py
> +sys.path.append("/home/aurmr/workspaces/uois_soofiyan_ws/src/segnetv2_mask2_former/UIE_main/mask2former_frame/")
This one is not resolved yet, right?

2023-05-09 00:13 UTC, markusgrotz commented on aurmr_unseen_object_clustering/src/aurmr_unseen_object_clustering/tools/match_masks.py
> +    print()
Remove (optional)

2023-05-09 00:13 UTC, markusgrotz commented on aurmr_unseen_object_clustering/src/aurmr_unseen_object_clustering/tools/run_network.py
> +UOC_PATH = '/home/aurmr/workspaces/uois_soofiyan_ws/src/aurmr_tahoma/aurmr_unseen_object_clustering/src/aurmr_unseen_object_clustering/'
See above

2023-05-09 00:13 UTC, markusgrotz commented on aurmr_perception/src/aurmr_perception/grasp_detection.py
> +        cv2.imwrite("/home/aurmr/workspaces/uois_soofiyan_ws/src/segnetv2_mask2_former/Mask_Results/grasp_pre_mask.png", cv_image)
See above

2023-09-22 17:15 UTC, nickswalker commented
Closing because it's unclear if this is still needed after #21

2023-09-22 17:15 UTC, closed without merging