March 2024 evaluation updates
au-rmr/aurmr_tahoma pull request #31
Opened 2024-04-23 21:33 UTC by nickswalker

This was the state of the code on the control machine as run during the last evaluation. We should merge this before the branch starts accumulating additional changes

2024-04-24 06:25 UTC, markusgrotz requested changes

2024-04-24 06:25 UTC, markusgrotz commented on aurmr_tasks/src/aurmr_tasks/common/motion.py
> -    def __init__(self, robot, default_pose=None):
Readded

2024-04-24 06:25 UTC, markusgrotz commented on aurmr_vacuum_gripper/vacuum_gripper_control/nodes/VacuumGripperSocketNode.py
These changes shouldn't be added

2024-04-24 06:27 UTC, markusgrotz commented
Can we revert https://github.com/au-rmr/aurmr_tahoma/pull/31/commits/b5b7922

2024-04-24 06:49 UTC, nickswalker commented
Yes, will change in the morning

2024-05-16 21:56 UTC, markusgrotz approved these changes

2024-05-16 21:56 UTC, merged